### PR TITLE
Added latest version of DeviceController

### PR DESCRIPTION
**Pull request by wildtayne**
Can now print a half torus!!

### CODE REVIEW

**Review by afig — APPROVED** [review]
I don't see any issues with bringing this into master.

**Comment by wildtayne** [comment]
Well, it might not actually work, so I'm probably going to hold off for a bit...

**Comment by ZBoylan** [comment]
Let us know when you think it is good.

**Comment by hanleycdavid** [comment]
I have a version I'm gonna test today.

**Pull request merged**
