### PR TITLE
Add first revision of DeviceController class and examples

### PR DESCRIPTION
**Pull request by wildtayne**
This PR adds the first revision of the DeviceController class, and an example sketch demonstrating its use. The sketch and class provide some documentation on how to use the class. 

It also contains a test mode, demonstrated in the example sketch, which lets the class run through the entire printing routine without sending any commands to a printer. This should allow the UI team to start integrating and testing the DeviceController class whenever they are ready, as most of the methods can be used in test mode without needing a printer attached to the test machine.

Also note that the DeviceController class now handles all threading and synchronization needed for printing. When a print job is started, it runs in a separate thread, allowing the UI to issue start/stop commands from the main thread.

Please let me know if you have any questions about the usage of this class.

### CODE REVIEW

**Comment by ZBoylan** [comment]
Looks good. Thanks for implementing multithreading and a test mode for the UI team.

- Is the comConnected variable needed when it will always be set to true when a DeviceController object is instantiated?  Or is testing that the connection to the printer was successful something that will be implemented later?

- I see there is a runWarmUp function and it is called by runPrintJob(). Should we remove the "warm up printer" button from the UI?

**Review by ZBoylan — APPROVED** [review]

**Comment by wildtayne** [comment]
- Thanks for pointing this out. `comConnected` is intended to be used with `disconnectSerial()`, which I've now realized I forgot to add (it should set `comConnected` to false). The idea is that when the disconnect method is called, the class will remember that it is disconnected. Otherwise, trying to send data over the disconnected serial would cause a crash. It is always set to true in the constructor, because the constructor will always throw an exception if the port is not connected (or be in test mode, so it doesn't matter).

- Yeah,  buttons for running the warm up/cool down code are not needed. However, there should be a button and some sort of slider or text box to set the preheat for the bed and extruder (`setPreheat()`). The warmup/cool down methods should probably be renamed to `runStart/StopCode`, which better reflects their function.

**Comment by wildtayne** [comment]
I forgot to post a comment last night - but I pushed a few more commits that address some of the ambiguity by adding 3 constructors and a matching `connectSerial()` method, as well as renaming warmup/cooldown to `runStartCode()` and `runEndCode()`, which is more correct. 

I updated the example to show how each constructor is used. Briefly, the three are:
1) For creating a `DeviceController` and connecting to a serial port immidiately
2) For creating a `DeviceController` in test mode (implies no serial connection)
3) For creating a `DeviceController` in normal mode, but connecting to a serial port later with `connectSerial()`

**Review by afig — APPROVED** [review]
Looks great. It's nice that your team was able to implement multi-threading for the print process.

Between all of the teams we'll have to sort out a way to maintain the `setup()` method. For now, I think it is okay to keep the test code in the `DeviceControl.pde` file.

**Pull request merged**
